# Solargraph configuration for this project
# Run Solargraph in Bundler context and index only relevant paths.
# See: https://solargraph.org/guides

version: 2
reporters:
  - rubocop

diagnostics: true

require:
  # List explicit requires if needed, otherwise Solargraph infers from Gemfile
  # - tosspayments/rails

plugins: []

# Use Bundler to resolve gems
bundler: true

# Exclude generated or irrelevant paths
exclude:
  - vendor
  - .git
  - node_modules
  - tmp
  - log
  - dist
  - coverage

# Map paths for the gem's lib
include:
  - lib/**/*.rb

# Formatting options (Solargraph-side; your editor may ignore some)
max_files: 5000

