source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 3.1.2'

# Rails 8
gem 'rails', '~> 8.0.0'

# Asset pipeline
gem 'propshaft'

# CSS framework
gem 'tailwindcss-rails'

# JavaScript
gem 'importmap-rails'

# Database
gem 'sqlite3', '>= 2.1'

# Server
gem 'puma', '>= 5.0'

# Hotwire
gem 'turbo-rails'
gem 'stimulus-rails'

# Build JSON APIs
gem 'jbuilder'

# Windows timezone data
gem 'tzinfo-data', platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants
# gem 'image_processing', '~> 1.2'

# Local gem for development
gem 'tosspayments-rails', path: '../tosspayments-rails'

group :development, :test do
  gem 'debug', platforms: %i[ mri windows ]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end

group :development do
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end